matrix:
  include:
  - language: java
    before_script:
      sudo apt-get install libgdcm2.8
      cd TBI-GUI
    script:
      - gradle test
  - language: python
    python:
      - '3.6'
    install:
      - sudo apt-get install libgdcm2.4
      - sudo apt-get install libgdcm-tools
      - pip install pydicom
      - pip install numpy
      - pip install tensorflow
      - pip install retrying
      - pip install dicom2nifti
      - pip install nibabel
    before_script: cd BSSCSFramework
    script:
      - python3 dicom_test_cases.py
      - python3 CTConverter/conversion_test_cases.py
